const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(require.resolve('playwright',{paths:[path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules')]}));
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'reports/screenshots'),BASE='http://127.0.0.1:4182';fs.mkdirSync(OUT,{recursive:true});
const report={checks:[],errors:[],requestsFailed:[],layouts:[]};const check=(s,b)=>{assert.ok(b,s);report.checks.push(s);console.log('PASS '+s)};
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{
const context=await browser.newContext({viewport:{width:1440,height:1050},reducedMotion:'reduce'}),page=await context.newPage();
page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)report.requestsFailed.push({url:r.url(),status:r.status()})});
await page.goto(BASE);await page.waitForFunction(()=>document.querySelector('#pagination button'));await page.evaluate(()=>document.fonts.ready);
check('93 articles in complete static HTML',await page.locator('#article-grid .article-card').count()===93);check('9 visible cards',await page.locator('#article-grid .article-card:visible').count()===9);
check('six topic icons',await page.locator('.topic-link svg').count()===6);check('four homepage principles',await page.locator('.principles h3').count()===4);
await page.locator('#pagination-top button[aria-label="Stránka 2"]').click();check('pagers synchronized',await page.locator('.pagination button[aria-current="page"]').evaluateAll(a=>a.length===2&&a.every(b=>b.textContent==='2')));
await page.locator('#month').selectOption('2026-08');check('month filter',await page.locator('#article-grid .article-card:visible').evaluateAll(a=>a.length>0&&a.every(c=>c.dataset.month==='2026-08')));check('month in URL',new URL(page.url()).searchParams.get('mesic')==='2026-08');check('month resets page',new URL(page.url()).searchParams.get('strana')===null);
await page.reload();await page.waitForFunction(()=>document.querySelector('#pagination button'));check('month reload',await page.locator('#month').inputValue()==='2026-08');await page.locator('#reset').click();check('month reset',await page.locator('#month').inputValue()==='');
await page.locator('#archiv').scrollIntoViewIfNeeded();check('sticky header',Math.abs((await page.locator('.header').boundingBox()).y)<1);await page.evaluate(()=>scrollTo(0,0));
check('no fictional published spisy',await page.locator('.preparing').count()===1&&await page.locator('.spis-card').count()===0);
await page.locator('#q').fill('Tremonton');await page.waitForTimeout(350);check('search title',await page.locator('#article-grid .article-card:visible').count()===1);check('search URL',new URL(page.url()).searchParams.get('q')==='Tremonton');
await page.reload();await page.waitForTimeout(300);check('filter restored from URL',await page.locator('#q').inputValue()==='Tremonton');
await page.locator('button[data-type="spekulace"]').click();check('combination empty',await page.locator('#empty').isVisible());await page.locator('#empty-reset').click();check('reset works',await page.locator('#article-grid .article-card:visible').count()===9&&new URL(page.url()).search==='');
await page.locator('#topic').selectOption('civilizace');await page.locator('button[data-type="spekulace"]').click();check('combined filters',await page.locator('#article-grid .article-card:visible').count()>0);check('all matching cards',await page.locator('#article-grid .article-card:visible').evaluateAll(a=>a.every(e=>e.dataset.category==='civilizace'&&e.dataset.type==='spekulace')));
await page.locator('#reset').click();await page.locator('#legacy-type').selectOption('franta');check('legacy type retained',await page.locator('#article-grid .article-card:visible').count()===5);await page.locator('#reset').click();
await page.locator('#pagination button[aria-label="Stránka 2"]').click();check('pagination URL',new URL(page.url()).searchParams.get('strana')==='2');await page.locator('#reset').click();
await page.locator('#q').fill('Newhouse');await page.waitForTimeout(300);check('full text search',await page.locator('#article-grid .article-card:visible').count()>0);await page.locator('#reset').click();
for(const w of [360,390,768,1280,1440]){await page.setViewportSize({width:w,height:w<600?844:1050});await page.goto(BASE);await page.waitForFunction(()=>document.querySelector('#pagination button'));await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('img')].filter(i=>i.getBoundingClientRect().width&&i.closest('[hidden]')===null).map(i=>{i.loading='eager';return i.decode().catch(()=>{})}))});const dims=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,bad:[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.right>innerWidth+1&&getComputedStyle(e).position!=='absolute'}).slice(0,5).map(e=>e.className)}));report.layouts.push({w,...dims});check('no horizontal overflow '+w,dims.scroll<=w+1);check('visible images loaded '+w,await page.locator('img:visible').evaluateAll(images=>images.every(i=>i.complete&&i.naturalWidth>0)));if([390,1440].includes(w)){await page.screenshot({path:path.join(OUT,'home-'+w+'.png'),fullPage:true});await page.screenshot({path:path.join(OUT,'viewport-'+w+'.png')})}if(w===390){await page.locator('.menu-toggle').click();check('mobile menu',await page.locator('#nav').isVisible());await page.keyboard.press('Escape');check('mobile menu escape',!await page.locator('#nav').isVisible())}}
await page.goto(BASE+'/clanky/tremonton-filmovy-dukaz-2026.html');check('article full text',await page.locator('.article-body').innerText().then(t=>t.length>1000));check('sources visible',await page.locator('.sources a').count()>0);check('article title',await page.title().then(t=>t.includes('Tremonton')));await page.screenshot({path:path.join(OUT,'article-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});check('article mobile overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(OUT,'article-mobile.png'),fullPage:true});
await page.goto(BASE+'/clanky/film.html');check('no video before activation',await page.locator('iframe').count()===0);check('video button exists',await page.locator('[data-video]').count()===1);await page.route('https://www.youtube-nocookie.com/**',route=>route.fulfill({status:200,contentType:'text/html',body:'<!doctype html><title>YouTube fixture</title>'}));await page.locator('[data-video]').click();check('video on activation',await page.locator('iframe').count()===1);
const nojs=await browser.newContext({javaScriptEnabled:false});const p=await nojs.newPage();await p.goto(BASE+'/clanky/tremonton-filmovy-dukaz-2026.html');check('article works without JS',(await p.locator('.article-body').innerText()).length>1000);await nojs.close();
check('no console or runtime errors',report.errors.length===0);check('no failed local assets',report.requestsFailed.length===0);
}finally{fs.writeFileSync(path.join(ROOT,'reports/browser-report.json'),JSON.stringify(report,null,2));await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
