(()=>{
 'use strict';
 const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#nav');
 menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Zavřít nabídku':'Otevřít nabídku');nav.classList.toggle('open',open)});
 nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav?.classList.contains('open')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus()}});
 for(const b of document.querySelectorAll('[data-video]'))b.addEventListener('click',()=>{const id=b.dataset.video;if(!/^[\w-]{11}$/.test(id))return;const f=document.createElement('iframe');f.src='https://www.youtube-nocookie.com/embed/'+id+'?autoplay=1';f.title='Video k článku';f.allow='autoplay; encrypted-media; picture-in-picture';f.allowFullscreen=true;b.replaceWith(f)});
 const form=document.querySelector('#filters');if(!form)return;
 const q=document.querySelector('#q'),topic=document.querySelector('#topic'),month=document.querySelector('#month'),legacy=document.querySelector('#legacy-type'),cards=[...document.querySelectorAll('#article-grid .article-card')],pagers=[...document.querySelectorAll('.pagination')],count=document.querySelector('#result-count'),empty=document.querySelector('#empty');
 let type='',page=1,index=null,pending=false;const size=9;
 const normal=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const indexPromise=fetch('/search.json').then(r=>{if(!r.ok)throw Error('search');return r.json()}).then(rows=>{index=new Map(rows.map(r=>[r.id,normal(r.text)]));return true}).catch(()=>{q.disabled=true;q.placeholder='Hledání se nepodařilo načíst. Obnovte stránku.';return false});
 function readUrl(){const params=new URLSearchParams(location.search);q.value=params.get('q')||'';topic.value=params.get('tema')||'';month.value=params.get('mesic')||'';type=params.get('typ')||'';if(!['','overeno','spekulace','svedectvi','franta','uap'].includes(type))type='';page=Math.max(1,Number.parseInt(params.get('strana')||'1',10)||1);legacy.value=['franta','uap'].includes(type)?type:''}
 function sync(){const params=new URLSearchParams();if(q.value.trim())params.set('q',q.value.trim());if(topic.value)params.set('tema',topic.value);if(month.value)params.set('mesic',month.value);if(type)params.set('typ',type);if(page>1)params.set('strana',String(page));const suffix=params.toString();const url=location.pathname+(suffix?'?'+suffix:'')+location.hash;if(url!==location.pathname+location.search+location.hash)history.replaceState(null,'',url)}
 function button(pager,label,target,disabled=false,current=false){const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=disabled;if(current)b.setAttribute('aria-current','page');b.setAttribute('aria-label',current?'Aktuální stránka '+target:label==='←'?'Předchozí stránka':label==='→'?'Další stránka':'Stránka '+target);b.addEventListener('click',()=>{page=target;render();document.querySelector('#archiv').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});document.querySelector('#archiv h2').setAttribute('tabindex','-1');document.querySelector('#archiv h2').focus({preventScroll:true})});pager.append(b)}
 async function render(update=true){const words=normal(q.value.trim()).split(/\s+/).filter(Boolean);if(words.length&&!index){if(pending)return;pending=true;await indexPromise;pending=false;if(!index)return}
 const found=cards.filter(c=>(!topic.value||c.dataset.category===topic.value)&&(!month.value||c.dataset.month===month.value)&&(!type||c.dataset.type===type)&&(!words.length||words.every(w=>index.get(c.dataset.id)?.includes(w))));
 const pages=Math.max(1,Math.ceil(found.length/size));page=Math.min(Math.max(1,page),pages);cards.forEach(c=>c.hidden=true);found.slice((page-1)*size,page*size).forEach(c=>c.hidden=false);
 count.textContent=found.length+' '+(found.length===1?'článek':found.length>1&&found.length<5?'články':'článků')+(q.value||type||topic.value||month.value?' podle výběru':' v archivu');empty.hidden=found.length>0;
 form.querySelectorAll('button[data-type]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.type===type)));legacy.value=['franta','uap'].includes(type)?type:'';
 for(const pager of pagers){pager.replaceChildren();pager.hidden=!found.length;if(found.length){button(pager,'←',page-1,page===1);for(let n=1;n<=pages;n++)if(n===1||n===pages||Math.abs(n-page)<=1)button(pager,String(n),n,false,n===page);else if(n===2&&page>3||n===pages-1&&page<pages-2){const s=document.createElement('span');s.textContent='…';s.setAttribute('aria-hidden','true');pager.append(s)}button(pager,'→',page+1,page===pages)}}
 if(update)sync();
 }
 let timer; q.addEventListener('input',()=>{page=1;clearTimeout(timer);timer=setTimeout(()=>render(),120)});topic.addEventListener('change',()=>{page=1;render()});month.addEventListener('change',()=>{page=1;render()});legacy.addEventListener('change',()=>{type=legacy.value;page=1;render()});form.querySelectorAll('button[data-type]').forEach(b=>b.addEventListener('click',()=>{type=b.dataset.type;page=1;render()}));
 function reset(){q.value='';topic.value='';month.value='';legacy.value='';type='';page=1;render()}
 form.addEventListener('reset',e=>{e.preventDefault();reset()});document.querySelector('#empty-reset').addEventListener('click',reset);form.addEventListener('submit',e=>{e.preventDefault();page=1;render()});window.addEventListener('popstate',()=>{readUrl();render(false)});
 readUrl();render();
})();
