/* Static, dependency-free maps. Sky is viewed from inside a sphere (ICRS/J2000). */
(function(){'use strict';
const M=window.MysteryMath,roots=[...document.querySelectorAll('[data-mystery-map]')];if(!roots.length)return;
const json=url=>fetch(url).then(r=>{if(!r.ok)throw Error('Map data '+r.status);return r.json();});
const cache=new Map(),get=url=>{if(!cache.has(url))cache.set(url,json(url));return cache.get(url);};
const names={'zeme':'Planeta Země','slunecni-soustava':'Sluneční soustava','hluboky-vesmir':'Hluboký vesmír'};
const bodies=[['Slunce',.06,.48,24,'#ffbc53'],['Merkur',.17,.48,6,'#908676'],['Venuše',.27,.48,10,'#d2a972'],['Země',.37,.48,11,'#486877'],['Mars',.47,.48,8,'#99613e'],['Jupiter',.58,.48,23,'#ac977b'],['Saturn',.70,.48,19,'#ab9e78'],['Uran',.81,.48,13,'#71a0ab'],['Neptun',.92,.48,13,'#526ba8'],['Měsíc',.37,.67,6,'#aaa9a3'],['Phobos',.44,.67,4,'#8c8172'],['Deimos',.49,.78,3,'#96836e'],['Pás asteroidů',.525,.26,4,'#a2a092'],['Europa',.57,.67,6,'#bbb5a3'],['Io',.62,.78,6,'#bd9a53'],['Titan',.72,.67,7,'#b58a40'],['Pluto',1.04,.48,6,'#c4b6a5'],['Quaoar',.90,.08,4,'#a7a7a0'],['Malá tělesa',.25,.16,4,'#82909a'],['Mezihvězdný prostor',.70,.90,4,'#657893']];
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const el=(tag,cls,text)=>{const x=document.createElement(tag);if(cls)x.className=cls;if(text!==undefined)x.textContent=text;return x;};
for(const root of roots)init(root);
async function init(root){
const stage=root.querySelector('.map-stage'),canvas=stage.querySelector('canvas'),ctx=canvas.getContext('2d'),layer=root.querySelector('.map-markers'),popup=root.querySelector('.map-popup'),list=root.querySelector('.map-results'),count=root.querySelector('.map-count'),note=root.querySelector('.map-note'),loading=root.querySelector('.map-loading'),input=root.querySelector('input'),preview=root.dataset.preview==='true';
let data=[],view='zeme',size=600,zoom=1,panX=0,panY=0,yaw=20,pitch=15,selected=null,selectedLocation=null,countries=null,stars=null,lines=null,constellations=null,frame=0,groups=[],gesture=null,dragged=false,popupGroup=[],popupIndex=0,epoch=0;
const pointers=new Map();
const motionQuery=window.matchMedia?.('(prefers-reduced-motion: reduce)');
let zoomTarget=null,zoomAnchor={x:0,y:0},lastTick=0;
function stopZoom(){zoomTarget=null;lastTick=0;}
function tickZoom(time){if(zoomTarget===null)return;const dt=lastTick?Math.min(48,time-lastTick):16;lastTick=time;const next=motionQuery?.matches?zoomTarget:zoom+(zoomTarget-zoom)*(1-Math.exp(-dt/65));const done=Math.abs(zoomTarget-next)<.002;applyZoom(done?zoomTarget:next,zoomAnchor.x,zoomAnchor.y);if(done)stopZoom();}

const schedule=()=>{if(!frame)frame=requestAnimationFrame(time=>{frame=0;tickZoom(time||lastTick+16);draw();if(zoomTarget!==null)schedule();});};
const local=e=>{const r=stage.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};};
function reset(){stopZoom();zoom=view==='slunecni-soustava'?.8:1;panX=panY=0;yaw=20;pitch=15;schedule();}
function point(loc){if(view==='zeme')return M.earth(loc.lon,loc.lat,size,zoom,panX,panY);if(view==='hluboky-vesmir')return M.sky(loc.ra,loc.dec,yaw,pitch,size,zoom);const b=bodies.find(b=>b[0]===loc.body);return b?{x:size/2+panX+(b[1]-.5)*size*zoom,y:size/2+panY+(b[2]-.5)*size*zoom}:null;}
function applyZoom(next,x=size/2,y=size/2){next=M.clamp(next,view==='slunecni-soustava'?.8:1,view==='hluboky-vesmir'?6:12);if(view!=='hluboky-vesmir'){panX=M.zoomAt(zoom,next,panX,x,size/2);panY=M.zoomAt(zoom,next,panY,y,size/2);bound();}zoom=next;bound();schedule();}
function changeZoom(next,x=size/2,y=size/2,smooth=true){if(!smooth||motionQuery?.matches){stopZoom();applyZoom(next,x,y);return;}zoomTarget=M.clamp(next,view==='slunecni-soustava'?.8:1,view==='hluboky-vesmir'?6:12);zoomAnchor={x,y};schedule();}
function bound(){panX=M.clamp(panX,-size*.6*zoom,size*.6*zoom);panY=M.clamp(panY,-size*.45*zoom,size*.45*zoom);pitch=M.clamp(pitch,-89,89);yaw=M.wrap(yaw);}
function pan(dx,dy){stopZoom();if(view==='hluboky-vesmir'){yaw+=dx*.13/zoom;pitch+=dy*.13/zoom;}else{panX+=dx;panY+=dy;}bound();schedule();}
function draw(){if(!ctx)return;ctx.clearRect(0,0,size,size);ctx.fillStyle='#080d15';ctx.fillRect(0,0,size,size);if(view==='zeme')drawEarth();else if(view==='slunecni-soustava')drawSolar();else drawSky();drawMarkers();root.querySelector('.map-coordinates').textContent=view==='hluboky-vesmir'?'J2000 / RA '+Math.round(yaw)+'° · DEC '+Math.round(pitch)+'°':view==='zeme'?'PLANETA ZEMĚ / '+zoom.toFixed(1)+'×':'SLUNEČNÍ SOUSTAVA / SCHÉMA';}
function strokePath(coords,project,close=false){let previous=null;ctx.beginPath();for(const coord of coords){const p=project(coord);if(!p){previous=null;continue;}if(!previous||Math.hypot(p.x-previous.x,p.y-previous.y)>size*1.3)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);previous=p;}if(close)ctx.closePath();}
function drawEarth(){const project=c=>M.earth(c[0],c[1],size,zoom,panX,panY);ctx.strokeStyle='#192633';ctx.lineWidth=.7;for(let lat=-90;lat<=90;lat+=30){strokePath([[-180,lat],[180,lat]],project);ctx.stroke();}for(let lon=-180;lon<=180;lon+=30){strokePath([[lon,-90],[lon,90]],project);ctx.stroke();}
if(!countries)return;ctx.lineWidth=.65;for(const f of countries.features){const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;ctx.beginPath();for(const poly of polys)for(const ring of poly){ring.forEach((c,i)=>{const p=project(c);if(i===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);});ctx.closePath();}ctx.fillStyle='#141d27';ctx.fill('evenodd');ctx.strokeStyle='#a86c2a';ctx.stroke();}
ctx.font='10px IBM Plex Mono, monospace';ctx.textAlign='center';ctx.textBaseline='middle';
const candidates=[],obstacles=[{left:12,top:12,right:225,bottom:48},{left:size-65,top:12,right:size-12,bottom:160},{left:size-55,top:size-70,right:size-12,bottom:size-12}];
// Leave the actual article markers clear, including the halos around new points.
for(const a of data.filter(a=>a.view==='zeme'))for(const loc of a.locations){const p=point(loc);obstacles.push({left:p.x-22,right:p.x+22,top:p.y-22,bottom:p.y+22});}
function label(id,text,p,priority,color){const metrics=ctx.measureText(text);const height=(metrics.actualBoundingBoxAscent||8)+(metrics.actualBoundingBoxDescent||3);candidates.push({id,text,...p,width:metrics.width,height,priority,color});}
if(zoom>=2)for(const f of countries.features){const rank=f.properties.labelRank||5;if(zoom<1.5+rank*.22)continue;label(f.properties.name,f.properties.nameCs,project([f.properties.lon,f.properties.lat]),rank,'#b38750');}
for(const [n,lon,lat] of [['ATLANTSKÝ OCEÁN',-35,10],['TICHÝ OCEÁN',-135,-15],['INDICKÝ OCEÁN',75,-30]])label(n,n,project([lon,lat]),99,'#536274');
for(const l of M.placeLabels(candidates,size,size,obstacles)){ctx.fillStyle=l.color;ctx.fillText(l.text,l.x,l.y);}
ctx.textBaseline='alphabetic';}
function drawSolar(){ctx.strokeStyle='#38404a';ctx.setLineDash([3,7]);const p=bodies.map(b=>point({body:b[0]}));ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);ctx.lineTo(p[16].x,p[16].y);ctx.stroke();ctx.setLineDash([]);
for(let i=0;i<bodies.length;i++){const b=bodies[i],pos=p[i],r=b[3]*Math.sqrt(zoom)*size/680;if(i>=9){const parent={'Měsíc':'Země',Phobos:'Mars',Deimos:'Mars',Europa:'Jupiter',Io:'Jupiter',Titan:'Saturn'}[b[0]];if(parent){const q=point({body:parent});ctx.beginPath();ctx.moveTo(q.x,q.y);ctx.lineTo(pos.x,pos.y);ctx.strokeStyle='#263340';ctx.stroke();}}
if(pos.x<-60||pos.x>size+60||pos.y<-60||pos.y>size+60)continue;const grad=ctx.createRadialGradient(pos.x-r*.35,pos.y-r*.4,0,pos.x,pos.y,r);grad.addColorStop(0,b[4]);grad.addColorStop(1,'#101722');ctx.fillStyle=grad;ctx.beginPath();ctx.arc(pos.x,pos.y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=b[4]+'99';ctx.lineWidth=.7;ctx.stroke();if(b[0]==='Saturn'){ctx.beginPath();ctx.ellipse(pos.x,pos.y,r*1.8,r*.48,-.3,0,Math.PI*2);ctx.stroke();}ctx.font=(i<9?'11':'9')+'px IBM Plex Sans, sans-serif';ctx.textAlign='center';ctx.fillStyle='#b1bac5';ctx.fillText(b[0],pos.x,pos.y+r+20);}}
function drawSky(){const project=c=>M.sky(c[0],c[1],yaw,pitch,size,zoom);ctx.strokeStyle='#182633';ctx.lineWidth=.65;for(let dec=-60;dec<=60;dec+=30){const coords=Array.from({length:181},(_,i)=>[i*2,dec]);strokePath(coords,project);ctx.stroke();}for(let ra=0;ra<360;ra+=30){strokePath(Array.from({length:91},(_,i)=>[ra,-90+i*2]),project);ctx.stroke();}
if(lines){ctx.strokeStyle='#ae782f88';ctx.lineWidth=.85;for(const f of lines.features)for(const coords of f.geometry.coordinates){strokePath(coords,project);ctx.stroke();}}
if(stars)for(const f of stars.features){const p=project(f.geometry.coordinates);if(!p||p.x<0||p.y<0||p.x>size||p.y>size)continue;ctx.fillStyle=Number(f.properties.bv)>.8?'#d8c9b2':'#c8d6e5';const r=M.clamp((6.5-Number(f.properties.mag))*.27,.4,2.3);ctx.globalAlpha=M.clamp((7-Number(f.properties.mag))*.19,.23,1);ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;
if(constellations){ctx.font='11px IBM Plex Mono, monospace';ctx.fillStyle='#b6a07b';ctx.textAlign='center';for(const f of constellations.features){const p=project(f.geometry.coordinates);if(p&&p.x>25&&p.x<size-25&&p.y>40&&p.y<size-30)ctx.fillText(f.properties.cz||f.properties.name,p.x,p.y);}}}
function drawMarkers(){const visible=[];for(const a of data.filter(a=>a.view===view))for(const loc of a.locations){const p=point(loc);if(p&&p.x>=8&&p.x<=size-8&&p.y>=8&&p.y<=size-8)visible.push({a,loc,p});}
groups=[];for(const x of visible){let g=groups.find(g=>Math.hypot(g.x-x.p.x,g.y-x.p.y)<26);if(!g){g={x:x.p.x,y:x.p.y,items:[]};groups.push(g);}if(!g.items.some(t=>t.a.id===x.a.id&&t.loc.place===x.loc.place))g.items.push(x);}
const old=new Map([...layer.children].map(b=>[b.dataset.key,b]));for(const g of groups){const key=g.items.map(x=>x.a.id+':'+x.loc.place).sort().join('|');let b=old.get(key);if(!b){b=el('button','map-point');b.type='button';b.dataset.key=key;b.append(el('span'));b.addEventListener('click',()=>{const current=groups.find(g=>g.items.map(x=>x.a.id+':'+x.loc.place).sort().join('|')===b.dataset.key);if(current){popupGroup=current.items;popupIndex=Math.max(0,popupGroup.findIndex(x=>x.a.id===selected));showPopup(popupGroup[popupIndex]);}});layer.append(b);}old.delete(key);b.style.left=g.x+'px';b.style.top=g.y+'px';b.dataset.multiple=String(g.items.length>1);b.querySelector('span').textContent=g.items.length>1?g.items.length:'';b.setAttribute('aria-label',g.items.map(x=>x.loc.place+' — '+x.a.title).join('; '));b.setAttribute('aria-pressed',String(g.items.some(x=>x.a.id===selected)));b.classList.toggle('is-region',g.items.every(x=>x.loc.precision==='region'));const pulse=M.pulse(g.items[0].a.date);b.classList.toggle('is-new',pulse.strength>0);b.style.setProperty('--pulse-strength',pulse.strength);b.style.setProperty('--pulse-duration',pulse.duration+'s');}for(const b of old.values())b.remove();}
function hidePopup(){popup.hidden=true;selected=null;selectedLocation=null;renderList();syncURL();schedule();}
function showPopup(item){selected=item.a.id;selectedLocation=item.loc;popup.replaceChildren();const close=el('button','map-popup-close');close.type='button';close.setAttribute('aria-label','Zavřít kartu článku');close.onclick=hidePopup;popup.append(close);const a=item.a;const hero=el('a');hero.href=a.url;hero.setAttribute('aria-label',a.title);if(a.image){const image=el('img');image.src=a.image;image.alt='';image.width=600;image.height=338;hero.append(image);}popup.append(hero);const copy=el('div','map-popup-copy');const time=el('time','',new Intl.DateTimeFormat('cs-CZ').format(new Date(a.date+'T12:00:00Z')));time.dateTime=a.date;copy.append(time);const h=el('h3'),title=el('a','',a.title);title.href=a.url;h.append(title);copy.append(h,el('p','map-place',item.loc?.place||'Bez doloženého umístění'),el('p','',a.description));const read=el('a','map-read','Číst článek →');read.href=a.url;copy.append(read);popup.append(copy);if(popupGroup.length>1){const pager=el('div','map-popup-pager');for(const direction of [-1,1]){const b=el('button','',direction<0?'←':'→');b.type='button';b.setAttribute('aria-label',direction<0?'Předchozí článek v místě':'Další článek v místě');b.onclick=()=>{popupIndex=(popupIndex+direction+popupGroup.length)%popupGroup.length;showPopup(popupGroup[popupIndex]);};if(direction<0)pager.append(b,el('span','',(popupIndex+1)+' / '+popupGroup.length));else pager.append(b);}popup.append(pager);}popup.hidden=false;note.textContent=item.loc?.note||a.note;renderList();syncURL();schedule();}
function focusArticle(a){stopZoom();selected=a.id;const loc=a.locations[0];selectedLocation=loc;popupGroup=[{a,loc}];popupIndex=0;if(loc){if(view==='hluboky-vesmir'){yaw=loc.ra;pitch=loc.dec;zoom=1.6;}else{zoom=view==='zeme'?3:2;panX=panY=0;const p=point(loc);panX=size/2-p.x;panY=size/2-p.y;}bound();}showPopup({a,loc});if(window.innerWidth<=850)stage.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});}
function syncURL(){const params=new URLSearchParams({mapa:view});if(selected)params.set('clanek',selected);const open=root.querySelector('.map-open');if(open)open.href='/mapa-zahad.html?'+params;if(!preview)history.replaceState(null,'',location.pathname+'?'+params);}
function renderList(){const q=normalize(input.value),filtered=data.filter(a=>a.view===view&&normalize(a.title+' '+a.locations.map(l=>l.place).join(' ')).includes(q));count.textContent=filtered.length+' článků · '+filtered.filter(a=>a.locations.length===0).length+' bez doloženého místa';list.replaceChildren();for(const a of filtered){const b=el('button','map-result');b.type='button';b.setAttribute('aria-pressed',String(a.id===selected));b.append(el('span','',a.title),el('small','',a.locations.map(l=>l.place).join(' · ')||'Bez přesného umístění'));b.onclick=()=>focusArticle(a);list.append(b);}if(!filtered.length)list.append(el('p','','Žádné stopy pro tento dotaz.'));}
async function setView(next,article=null){view=next;const ticket=++epoch;reset();popup.hidden=true;selected=null;selectedLocation=null;for(const b of root.querySelectorAll('[data-map-view]'))b.setAttribute('aria-pressed',String(b.dataset.mapView===view));note.textContent=view==='zeme'?'Regionální body označují širší oblast. Přesnost je uvedená v kartě každého místa.':view==='slunecni-soustava'?'Schematické pořadí planet a jejich měsíců. Velikosti, rozestupy a body nejsou aktuální oběžné polohy.':'Otáčejte pohledem o 360°. Skutečné polohy hvězd a souhvězdí · J2000/ICRS; směr, nikoli vzdálenost.';renderList();loading.hidden=false;
try{if(view==='zeme')countries=await get('/assets/maps/countries.json');if(view==='hluboky-vesmir')[stars,lines,constellations]=await Promise.all([get('/assets/maps/stars.json'),get('/assets/maps/constellation-lines.json'),get('/assets/maps/constellations.json')]);if(ticket!==epoch)return;loading.hidden=true;schedule();syncURL();if(article){const a=data.find(a=>a.id===article&&a.view===view);if(a)focusArticle(a);else note.textContent='Tento článek v mapě není dostupný.';}}catch(err){if(ticket!==epoch)return;loading.textContent='Mapu se nepodařilo načíst. Obnovte stránku; články jsou dostupné v seznamu.';console.error(err);}}
root.querySelectorAll('[data-map-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.mapView)));
root.querySelectorAll('[data-map-action]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.mapAction==='reset'){reset();hidePopup();syncURL();}else changeZoom((zoomTarget??zoom)*(b.dataset.mapAction==='in'?1.4:1/1.4));}));input.addEventListener('input',renderList);
stage.addEventListener('wheel',e=>{if(e.target.closest('.map-popup'))return;e.preventDefault();const p=local(e);changeZoom((zoomTarget??zoom)*Math.exp(-M.clamp(e.deltaY,-300,300)*.0018),p.x,p.y);},{passive:false});
stage.addEventListener('pointerdown',e=>{if(e.target.closest('button,a,.map-popup'))return;if(e.pointerType==='mouse'&&e.button!==0)return;stopZoom();stage.setPointerCapture(e.pointerId);pointers.set(e.pointerId,local(e));gesture=pointers.size===2?M.pinch([...pointers.values()]):local(e);dragged=false;});
stage.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const p=local(e);pointers.set(e.pointerId,p);if(pointers.size===2){const next=M.pinch([...pointers.values()]);if(gesture?.distance){pan(next.x-gesture.x,next.y-gesture.y);changeZoom(zoom*next.distance/Math.max(1,gesture.distance),next.x,next.y,false);}gesture=next;dragged=true;}else if(pointers.size===1&&gesture){const dx=p.x-gesture.x,dy=p.y-gesture.y;if(Math.abs(dx)+Math.abs(dy)>1)dragged=true;pan(dx,dy);gesture=p;}});
const end=e=>{pointers.delete(e.pointerId);gesture=pointers.size===1?[...pointers.values()][0]:null;};stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end);stage.addEventListener('lostpointercapture',end);
stage.addEventListener('keydown',e=>{if(e.target!==stage)return;if(e.key==='Escape'){hidePopup();return;}if(['+','=','-','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key)){e.preventDefault();if(e.key==='+'||e.key==='=')changeZoom((zoomTarget??zoom)*1.4);else if(e.key==='-')changeZoom((zoomTarget??zoom)/1.4);else if(e.key==='Home')reset();else pan(e.key==='ArrowLeft'?40:e.key==='ArrowRight'?-40:0,e.key==='ArrowUp'?40:e.key==='ArrowDown'?-40:0);}});
new ResizeObserver(()=>{const old=size;size=stage.clientWidth;if(size<=0)return;panX*=size/old;panY*=size/old;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(size*dpr);canvas.height=Math.round(size*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);schedule();}).observe(stage);
document.fonts?.ready.then(schedule);
// Update age at Prague midnight, including tabs left open for several days.
setInterval(()=>{if(!document.hidden)schedule();},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule();});
try{data=await get('/web/map-articles.json');const params=new URLSearchParams(location.search),id=params.get('clanek'),article=data.find(a=>a.id===id);await setView(article?.view||(!preview&&names[params.get('mapa')]?params.get('mapa'):'zeme'),preview?null:id);}catch(err){loading.textContent='Nepodařilo se načíst články. Zkuste obnovit stránku.';console.error(err);}
}
})();
